[package]
name = "proj2"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "lexer", "parser", "stdlib", "turtlelib"
]

[dependencies]
lexer = { path = "lexer" }
parser = { path = "parser" }
stdlib = { path = "stdlib" }
turtlelib = { path = "turtlelib" }
